name: api-proy
services:
    web:
        build: .
        ports:
        - 8000:8000
        restart: always
        logging:
            options:
                max-size: 1g
        image: a01229632/proy-apis:latest